package net.unit8.souther.runtime;

import net.unit8.raoh.Err;
import net.unit8.raoh.Issue;
import net.unit8.raoh.Issues;
import net.unit8.raoh.Ok;
import net.unit8.raoh.Path;

import net.unit8.souther.runtime.DecodeError.PathElement;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;

/**
 * The decoder facade that Souther-generated bytecode calls. It routes primitive reads
 * through Raoh and converts Raoh's issue model into Souther's {@link DecodeError} /
 * {@link NonEmptyList}, so the compiler never needs to know Raoh's API and Raoh types
 * never leak into the generated public surface (spec sections 10.1, 10.6, 28).
 */
public final class Decoders {

    private Decoders() {}

    // --- Raoh primitive decoders (the runtime's single point of contact with Raoh) ---

    private static final net.unit8.raoh.decode.Decoder<Object, String> RAOH_TEXT =
            (in, path) -> in instanceof String s
                    ? net.unit8.raoh.Result.ok(s)
                    : net.unit8.raoh.Result.fail(path, "expected_text", "expected a text value");

    private static final net.unit8.raoh.decode.Decoder<Object, Long> RAOH_INT =
            (in, path) -> switch (in) {
                case Long l -> net.unit8.raoh.Result.ok(l);
                case Integer i -> net.unit8.raoh.Result.ok((long) i);
                case null, default ->
                        net.unit8.raoh.Result.fail(path, "expected_int", "expected an integer value");
            };

    /** Reads a {@code Raw.Text} as a {@code String}. Called by generated {@code decode} bodies. */
    public static Result<String, NonEmptyList<DecodeError>> text(Raw raw) {
        return fromRaoh(RAOH_TEXT.decode(toJava(raw), Path.ROOT));
    }

    /** Reads a {@code Raw.Int} as a {@code long}. Called by generated {@code decode} bodies. */
    public static Result<Long, NonEmptyList<DecodeError>> integer(Raw raw) {
        return fromRaoh(RAOH_INT.decode(toJava(raw), Path.ROOT));
    }

    /**
     * Builds a single-error failure at the root path. Called by generated code for
     * {@code require ... else Code} and for invariant violations during construction.
     */
    public static <T> Result<T, NonEmptyList<DecodeError>> fail(String code, String message) {
        return Result.err(NonEmptyList.of(DecodeError.atRoot(code, message)));
    }

    // --- object fields and applicative accumulation (spec 10.3, 15, 27.7) ---

    /** Reads the string-valued field {@code key} from a {@code Raw.Object}. */
    public static Result<String, NonEmptyList<DecodeError>> stringField(Raw raw, String key) {
        return field(raw, key, Decoders::text);
    }

    /** Reads the int-valued field {@code key} from a {@code Raw.Object}. */
    public static Result<Long, NonEmptyList<DecodeError>> longField(Raw raw, String key) {
        return field(raw, key, Decoders::integer);
    }

    /** Reads the field {@code key} from a {@code Raw.Object} with a nested decoder. */
    public static <T> Result<T, NonEmptyList<DecodeError>> objectField(
            Raw raw, String key, Decoder<T> inner) {
        return field(raw, key, child -> toResult(inner.decode(child)));
    }

    /** The primitive text decoder as a {@link Decoder} (for list elements and nesting). */
    public static Decoder<String> textDecoder() {
        return raw -> finish(text(raw));
    }

    /** The primitive int decoder as a {@link Decoder}. */
    public static Decoder<Long> intDecoder() {
        return raw -> finish(integer(raw));
    }

    /** The decoder boundary value {@code T | 復号失敗}: the value on success, a
     * {@link DecodeFailure} on failure. Called at the end of every generated {@code decode}. */
    public static Object finish(Result<?, NonEmptyList<DecodeError>> r) {
        return switch (r) {
            case Result.Ok<?, NonEmptyList<DecodeError>> ok -> ok.value();
            case Result.Err<?, NonEmptyList<DecodeError>> err -> new DecodeFailure(err.error());
        };
    }

    /** Wraps accumulated errors as the {@code 復号失敗} arm. Called by generated object decoders. */
    public static Object decodeFailure(NonEmptyList<DecodeError> errors) {
        return new DecodeFailure(errors);
    }

    /** Converts a nested decoder's boundary value ({@code T | 復号失敗}) back to the internal
     * accumulating Result so combinators can merge errors. */
    @SuppressWarnings("unchecked")
    private static <T> Result<T, NonEmptyList<DecodeError>> toResult(Object decoded) {
        if (decoded instanceof DecodeFailure df) {
            return Result.err(df.errors());
        }
        return Result.ok((T) decoded);
    }

    /** Builds a decoder for {@code List<T>} that applies {@code element} to each item,
     *  accumulating errors with {@code [index]} paths (spec sections 7.2, 15). */
    public static <T> Decoder<List<T>> listOf(Decoder<T> element) {
        return raw -> {
            if (!(raw instanceof Raw.ListValue lv)) {
                return new DecodeFailure(NonEmptyList.of(
                        DecodeError.atRoot("expected_list", "expected a list")));
            }
            List<T> values = new ArrayList<>();
            List<DecodeError> errors = new ArrayList<>();
            int i = 0;
            for (Raw item : lv.value()) {
                switch (Decoders.<T>toResult(element.decode(item))) {
                    case Result.Ok<T, NonEmptyList<DecodeError>> ok -> values.add(ok.value());
                    case Result.Err<T, NonEmptyList<DecodeError>> err -> {
                        for (DecodeError e : err.error().toList()) {
                            List<PathElement> path = new ArrayList<>();
                            path.add(new PathElement.Index(i));
                            path.addAll(e.path());
                            errors.add(new DecodeError(path, e.code(), e.message()));
                        }
                    }
                }
                i++;
            }
            if (!errors.isEmpty()) {
                return new DecodeFailure(new NonEmptyList<>(errors.get(0), errors.subList(1, errors.size())));
            }
            return List.copyOf(values);
        };
    }

    /**
     * Discriminated decode: reads the string field {@code key}, matches it against
     * {@code tag}, and if it matches runs {@code inner}. Returns {@code null} when the
     * tag does not match, so generated code can try the next variant (spec section 10.4).
     */
    public static Object variant(Raw raw, String key, String tag, Decoder<?> inner) {
        return tag.equals(discriminant(raw, key)) ? inner.decode(raw) : null;
    }

    /** Reads the discriminant field as a string, accepting either a text or an integer value. */
    private static String discriminant(Raw raw, String key) {
        if (raw instanceof Raw.ObjectValue obj) {
            Raw v = obj.value().get(key);
            if (v instanceof Raw.TextValue t) {
                return t.value();
            }
            if (v instanceof Raw.IntValue i) {
                return Long.toString(i.value());
            }
        }
        return null;
    }

    /** The {@code 復号失敗} arm returned when no discriminator variant matched (spec section 10.4). */
    public static Object noVariant(String key) {
        return new DecodeFailure(NonEmptyList.of(
                new DecodeError(List.of(new PathElement.Field(key)), "no_variant", "no variant matched")));
    }

    private static <T> Result<T, NonEmptyList<DecodeError>> field(
            Raw raw, String key, Function<Raw, Result<T, NonEmptyList<DecodeError>>> inner) {
        if (!(raw instanceof Raw.ObjectValue obj)) {
            return fail("expected_object", "expected an object");
        }
        Raw child = obj.value().get(key);
        if (child == null) {
            return Result.err(NonEmptyList.of(
                    new DecodeError(List.of(new PathElement.Field(key)), "required", "is required")));
        }
        return switch (inner.apply(child)) {
            case Result.Ok<T, NonEmptyList<DecodeError>> ok -> ok;
            case Result.Err<T, NonEmptyList<DecodeError>> err ->
                    Result.err(prefix(key, err.error()));
        };
    }

    private static NonEmptyList<DecodeError> prefix(String key, NonEmptyList<DecodeError> errors) {
        List<DecodeError> prefixed = new ArrayList<>();
        for (DecodeError e : errors.toList()) {
            List<PathElement> path = new ArrayList<>();
            path.add(new PathElement.Field(key));
            path.addAll(e.path());
            prefixed.add(new DecodeError(path, e.code(), e.message()));
        }
        return new NonEmptyList<>(prefixed.get(0), prefixed.subList(1, prefixed.size()));
    }

    /**
     * Merges the failures of the given results, accumulating every error. Returns
     * {@code null} when all results are {@code Ok} — the signal generated code uses to
     * proceed to construction (spec section 15, applicative accumulation).
     */
    @SafeVarargs
    public static NonEmptyList<DecodeError> mergeErrors(Result<?, NonEmptyList<DecodeError>>... results) {
        List<DecodeError> all = new ArrayList<>();
        for (Result<?, NonEmptyList<DecodeError>> r : results) {
            if (r instanceof Result.Err<?, NonEmptyList<DecodeError>> err) {
                all.addAll(err.error().toList());
            }
        }
        if (all.isEmpty()) {
            return null;
        }
        return new NonEmptyList<>(all.get(0), all.subList(1, all.size()));
    }

    // --- Raoh <-> Souther conversion ---

    private static Object toJava(Raw raw) {
        return switch (raw) {
            case Raw.TextValue t -> t.value();
            case Raw.IntValue i -> i.value();
            case Raw.BoolValue b -> b.value();
            case Raw.DecimalValue d -> d.value();
            case Raw.ListValue l -> l.value();
            case Raw.ObjectValue o -> o.value();
            case Raw.NullValue ignored -> null;
        };
    }

    private static <X> Result<X, NonEmptyList<DecodeError>> fromRaoh(net.unit8.raoh.Result<X> r) {
        return switch (r) {
            case Ok<X> ok -> Result.ok(ok.value());
            case Err<X> err -> Result.err(toNonEmptyList(err.issues()));
        };
    }

    private static NonEmptyList<DecodeError> toNonEmptyList(Issues issues) {
        List<DecodeError> errors = new ArrayList<>();
        for (Issue issue : issues.asList()) {
            errors.add(toDecodeError(issue));
        }
        // Raoh guarantees a failed result carries at least one issue.
        return new NonEmptyList<>(errors.get(0), errors.subList(1, errors.size()));
    }

    private static DecodeError toDecodeError(Issue issue) {
        List<PathElement> path = new ArrayList<>();
        for (String segment : issue.path().segments()) {
            path.add(new PathElement.Field(segment));
        }
        return new DecodeError(path, issue.code(), issue.message());
    }
}
