package net.unit8.souther.runtime;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Encoder helpers that Souther-generated bytecode calls. The inverse of the decoder's
 * discriminator: {@link #tagged} adds the discriminant field to an arm's encoded object
 * (spec sections 10.4, 11).
 */
public final class Encoders {

    private Encoders() {}

    /** Returns the arm's encoded object with {@code key: tag} added at the front. */
    public static Raw tagged(Raw armRaw, String key, String tag) {
        if (armRaw instanceof Raw.ObjectValue obj) {
            Map<String, Raw> merged = new LinkedHashMap<>();
            merged.put(key, Raw.text(tag));
            merged.putAll(obj.value());
            return Raw.object(merged);
        }
        return armRaw;
    }
}
