package net.unit8.souther.runtime;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Encoder helpers that Souther-generated bytecode calls. The inverse of the decoder's
 * discriminator: {@link #tagged} adds the discriminant field to an arm's encoded object
 * (spec sections 10.4, 11).
 */
public final class Encoders {

    private Encoders() {}

    /** The primitive text encoder as an {@link Encoder} (for list elements). */
    public static Encoder<String> textEncoder() {
        return Raw::text;
    }

    /** The primitive int encoder as an {@link Encoder}. */
    public static Encoder<Long> intEncoder() {
        return v -> Raw.integer(v);
    }

    /** Encodes a {@code List<T>} to a {@code Raw.List} by applying {@code element} to each item. */
    public static Raw encodeList(List<?> values, Encoder<Object> element) {
        List<Raw> out = new ArrayList<>(values.size());
        for (Object v : values) {
            out.add(element.encode(v));
        }
        return Raw.list(out);
    }

    /** Encodes a {@code Map<String, T>} to a {@code Raw.Object} by applying {@code value} to each entry. */
    public static Raw encodeMap(Map<String, ?> map, Encoder<Object> value) {
        Map<String, Raw> out = new LinkedHashMap<>();
        for (Map.Entry<String, ?> e : map.entrySet()) {
            out.put(e.getKey(), value.encode(e.getValue()));
        }
        return Raw.object(out);
    }

    /** Returns the arm's encoded object with {@code key: tag} added at the front. */
    public static Raw tagged(Raw armRaw, String key, String tag) {
        if (armRaw instanceof Raw.ObjectValue obj) {
            Map<String, Raw> merged = new LinkedHashMap<>();
            merged.put(key, Raw.text(tag));
            merged.putAll(obj.value());
            return Raw.object(merged);
        }
        return armRaw;
    }
}
