package net.unit8.souther.runtime;

import java.util.List;

/** List helpers the generated bytecode calls (spec 18.4). */
public final class Lists {

    private Lists() {}

    /** Safe indexing: {@code Some(element)} when {@code index} is in range, else {@code None}. */
    public static <T> Option<T> get(List<T> list, long index) {
        if (index < 0 || index >= list.size()) {
            return Option.none();
        }
        return Option.some(list.get((int) index));
    }
}
