package net.unit8.souther.runtime;

import java.util.ArrayList;
import java.util.List;

/** List helpers the generated bytecode calls (spec 18.4). */
public final class Lists {

    private Lists() {}

    /** Safe indexing: {@code Some(element)} when {@code index} is in range, else {@code None}. */
    public static <T> Option<T> get(List<T> list, long index) {
        if (index < 0 || index >= list.size()) {
            return Option.none();
        }
        return Option.some(list.get((int) index));
    }

    /** Immutable concatenation of two lists (spec 18.4, the {@code ++} operator). */
    public static <T> List<T> concat(List<? extends T> a, List<? extends T> b) {
        List<T> out = new ArrayList<>(a.size() + b.size());
        out.addAll(a);
        out.addAll(b);
        return List.copyOf(out);
    }
}
