package net.unit8.souther.runtime;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/** Map helpers the generated bytecode calls (spec 18.5). Keys are always String (spec 7.2). */
public final class Maps {

    private Maps() {}

    /** {@code Some(value)} when {@code key} is present, else {@code None}. */
    public static <V> Option<V> get(Map<String, V> map, String key) {
        return map.containsKey(key) ? Option.some(map.get(key)) : Option.none();
    }

    public static boolean containsKey(Map<String, ?> map, String key) {
        return map.containsKey(key);
    }

    public static List<String> keys(Map<String, ?> map) {
        return List.copyOf(map.keySet());
    }

    public static <V> List<V> values(Map<String, V> map) {
        return new ArrayList<>(map.values());
    }
}
