package net.unit8.souther.runtime;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Map helpers the generated bytecode calls (spec 18.5). Keys are always String (spec 7.2).
 *  The building operations return a fresh immutable map in insertion order (Map is immutable,
 *  spec collections) and never mutate the input. */
public final class Maps {

    private Maps() {}

    /** The empty map. Its value type is fixed by context (the {@code Map.empty} built-in), like the
     *  empty list; at runtime it is element-agnostic. */
    public static Map<String, ?> empty() {
        return Map.of();
    }

    /** A one-entry map. */
    public static <V> Map<String, V> singleton(String key, V value) {
        LinkedHashMap<String, V> out = new LinkedHashMap<>();
        out.put(key, value);
        return Collections.unmodifiableMap(out);
    }

    /** {@code m} with {@code key} set to {@code value} (added, or overwriting an existing entry). */
    public static <V> Map<String, V> insert(String key, V value, Map<String, V> m) {
        LinkedHashMap<String, V> out = new LinkedHashMap<>(m);
        out.put(key, value);
        return Collections.unmodifiableMap(out);
    }

    /** {@code m} without {@code key}; {@code m} unchanged when the key is absent. */
    public static <V> Map<String, V> remove(String key, Map<String, V> m) {
        if (!m.containsKey(key)) {
            return m;
        }
        LinkedHashMap<String, V> out = new LinkedHashMap<>(m);
        out.remove(key);
        return Collections.unmodifiableMap(out);
    }

    public static boolean isEmpty(Map<String, ?> m) {
        return m.isEmpty();
    }

    public static long size(Map<String, ?> m) {
        return m.size();
    }

    /** {@code Some(value)} when {@code key} is present, else {@code None}. */
    public static <V> Option<V> get(Map<String, V> map, String key) {
        return map.containsKey(key) ? Option.some(map.get(key)) : Option.none();
    }

    public static boolean containsKey(Map<String, ?> map, String key) {
        return map.containsKey(key);
    }

    public static List<String> keys(Map<String, ?> map) {
        return List.copyOf(map.keySet());
    }

    public static <V> List<V> values(Map<String, V> map) {
        return new ArrayList<>(map.values());
    }
}
