package net.unit8.souther.runtime;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Map helpers the generated bytecode calls (spec 18.5). A key is a String or a String-backed
 *  newtype value (ADR-0040), compared by value equality (ADR-0009), so keys are typed {@code Object}
 *  here. The building operations return a fresh immutable map in insertion order (Map is immutable,
 *  spec collections) and never mutate the input. */
public final class Maps {

    private Maps() {}

    /** The empty map. Its key and value types are fixed by context (the {@code Map.empty} built-in),
     *  like the empty list; at runtime it is element-agnostic. */
    public static Map<Object, ?> empty() {
        return Map.of();
    }

    /** A one-entry map. */
    public static <K, V> Map<K, V> singleton(K key, V value) {
        LinkedHashMap<K, V> out = new LinkedHashMap<>();
        out.put(key, value);
        return Collections.unmodifiableMap(out);
    }

    /** {@code m} with {@code key} set to {@code value} (added, or overwriting an existing entry). */
    public static <K, V> Map<K, V> insert(K key, V value, Map<K, V> m) {
        LinkedHashMap<K, V> out = new LinkedHashMap<>(m);
        out.put(key, value);
        return Collections.unmodifiableMap(out);
    }

    /** {@code m} without {@code key}; {@code m} unchanged when the key is absent. */
    public static <K, V> Map<K, V> remove(K key, Map<K, V> m) {
        if (!m.containsKey(key)) {
            return m;
        }
        LinkedHashMap<K, V> out = new LinkedHashMap<>(m);
        out.remove(key);
        return Collections.unmodifiableMap(out);
    }

    public static boolean isEmpty(Map<?, ?> m) {
        return m.isEmpty();
    }

    public static long size(Map<?, ?> m) {
        return m.size();
    }

    /** The entries as a list of {@code (key, value)} tuples, each an {@code Object[]} (ADR-0036),
     *  in the map's iteration order. */
    public static <K, V> List<Object[]> toList(Map<K, V> m) {
        List<Object[]> out = new ArrayList<>(m.size());
        for (Map.Entry<K, V> e : m.entrySet()) {
            out.add(new Object[]{e.getKey(), e.getValue()});
        }
        return List.copyOf(out);
    }

    /** A map from a list of {@code (key, value)} tuples; a later entry overwrites an earlier one
     *  with the same key. */
    @SuppressWarnings("unchecked")
    public static <K, V> Map<K, V> fromList(List<Object[]> entries) {
        LinkedHashMap<K, V> out = new LinkedHashMap<>();
        for (Object[] e : entries) {
            out.put((K) e[0], (V) e[1]);
        }
        return Collections.unmodifiableMap(out);
    }

    /** {@code Some(value)} when {@code key} is present, else {@code None}. */
    public static <V> Option<V> get(Map<?, V> map, Object key) {
        return map.containsKey(key) ? Option.some(map.get(key)) : Option.none();
    }

    public static boolean containsKey(Map<?, ?> map, Object key) {
        return map.containsKey(key);
    }

    public static List<Object> keys(Map<?, ?> map) {
        return List.copyOf(map.keySet());
    }

    public static <V> List<V> values(Map<?, V> map) {
        return new ArrayList<>(map.values());
    }

    /** {@code m} with every key rewritten by {@code keyFn}, values unchanged, in iteration order.
     *  The encoder uses it to render a {@code Map<商品ID, V>}'s keys bare (each key's {@code value})
     *  before the boundary map encoder writes a {@code String}-keyed object. */
    public static <K, V> Map<Object, V> mapKeys(Map<K, V> m, java.util.function.Function<K, ?> keyFn) {
        LinkedHashMap<Object, V> out = new LinkedHashMap<>();
        for (Map.Entry<K, V> e : m.entrySet()) {
            out.put(keyFn.apply(e.getKey()), e.getValue());
        }
        return Collections.unmodifiableMap(out);
    }
}
