package net.unit8.souther.runtime;

import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/** Set helpers the generated bytecode calls. A Set is unordered with no duplicates, compared by the
 *  elements' value equality (spec collections, ADR-0009). Every operation returns a fresh immutable
 *  set (insertion order preserved for a stable {@code toList} / encode) and never mutates its input.
 *  This class is Raoh-free; {@link #fromList} is also the dedup a Set decoder maps a list through. */
public final class Sets {

    private Sets() {}

    /** The empty set; its element type is fixed by context (the {@code Set.empty} built-in). */
    public static Set<?> empty() {
        return Set.of();
    }

    public static <T> Set<T> singleton(T value) {
        LinkedHashSet<T> s = new LinkedHashSet<>();
        s.add(value);
        return Collections.unmodifiableSet(s);
    }

    public static <T> Set<T> insert(T value, Set<T> s) {
        LinkedHashSet<T> out = new LinkedHashSet<>(s);
        out.add(value);
        return Collections.unmodifiableSet(out);
    }

    public static <T> Set<T> remove(T value, Set<T> s) {
        if (!s.contains(value)) {
            return s;
        }
        LinkedHashSet<T> out = new LinkedHashSet<>(s);
        out.remove(value);
        return Collections.unmodifiableSet(out);
    }

    public static boolean contains(Object value, Set<?> s) {
        return s.contains(value);
    }

    public static <T> Set<T> union(Set<T> a, Set<T> b) {
        LinkedHashSet<T> out = new LinkedHashSet<>(a);
        out.addAll(b);
        return Collections.unmodifiableSet(out);
    }

    public static <T> Set<T> intersect(Set<T> a, Set<T> b) {
        LinkedHashSet<T> out = new LinkedHashSet<>(a);
        out.retainAll(b);
        return Collections.unmodifiableSet(out);
    }

    /** The elements of {@code a} that are not in {@code b}. */
    public static <T> Set<T> difference(Set<T> a, Set<T> b) {
        LinkedHashSet<T> out = new LinkedHashSet<>(a);
        out.removeAll(b);
        return Collections.unmodifiableSet(out);
    }

    public static boolean isEmpty(Set<?> s) {
        return s.isEmpty();
    }

    public static long size(Set<?> s) {
        return s.size();
    }

    public static <T> List<T> toList(Set<T> s) {
        return List.copyOf(s);
    }

    /** A set from a list, dropping duplicates and keeping first-seen order. Also the map a derived
     *  Set decoder applies to the list it decodes. */
    public static <T> Set<T> fromList(List<T> xs) {
        return Collections.unmodifiableSet(new LinkedHashSet<>(xs));
    }
}
