package net.unit8.souther.runtime;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

/** String helpers the generated bytecode calls (spec 18.1). These back the {@code souther.string}
 *  intrinsics that a single JVM {@code String} method does not already cover. */
public final class Strings {

    /** Runs of whitespace, for {@link #words} — compiled once rather than per call. */
    private static final Pattern WHITESPACE = Pattern.compile("\\s+");

    private Strings() {}

    /** Splits on a literal separator, keeping empty pieces (Elm {@code String.split} semantics):
     *  {@code split("a,,b", ",") == ["a", "", "b"]}. An empty separator yields the whole string. */
    public static List<String> split(String s, String sep) {
        if (sep.isEmpty()) {
            return List.of(s);
        }
        List<String> out = new ArrayList<>();
        int from = 0;
        while (true) {
            int at = s.indexOf(sep, from);
            if (at < 0) {
                out.add(s.substring(from));
                break;
            }
            out.add(s.substring(from, at));
            from = at + sep.length();
        }
        return List.copyOf(out);
    }

    /** Joins with a separator ({@code join(["a", "b"], "-") == "a-b"}). */
    public static String join(List<String> xs, String sep) {
        return String.join(sep, xs);
    }

    /** Joins a list of strings with no separator (Elm {@code String.concat}):
     *  {@code concat(["a", "b", "c"]) == "abc"}. This is {@code join(xs, "")}. */
    public static String concat(List<String> xs) {
        return join(xs, "");
    }

    /** Replaces every literal occurrence of {@code target} (Elm {@code String.replace}). An empty
     *  {@code target} leaves the string unchanged rather than splicing between every character. */
    public static String replace(String s, String target, String replacement) {
        if (target.isEmpty()) {
            return s;
        }
        return s.replace(target, replacement);
    }

    /** Renders an integer as its decimal string ({@code fromInt(42) == "42"}). */
    public static String fromInt(long n) {
        return Long.toString(n);
    }

    /** Splits on runs of whitespace, dropping empty pieces (Elm {@code String.words}):
     *  {@code words("  a  b ") == ["a", "b"]}. */
    public static List<String> words(String s) {
        List<String> out = new ArrayList<>();
        for (String w : WHITESPACE.split(s)) {
            if (!w.isEmpty()) {
                out.add(w);
            }
        }
        return List.copyOf(out);
    }
}
