package net.unit8.souther.compiler;

import net.unit8.souther.compiler.ast.Ast;
import net.unit8.souther.compiler.check.Type;
import net.unit8.souther.compiler.check.TypeChecker;
import net.unit8.souther.compiler.diag.CompileException;
import net.unit8.souther.compiler.diag.Diagnostic;
import net.unit8.souther.compiler.diag.SourcePos;

import net.unit8.raoh.Err;
import net.unit8.raoh.Ok;
import net.unit8.raoh.Result;
import net.unit8.raoh.decode.Decoder;
import net.unit8.raoh.decode.ObjectDecoders;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Evaluates a module's {@code example}s at compile time and reports any mismatch as a compile error.
 * It mirrors {@link Runner}: it decodes each row's input expressions into the target
 * behavior's parameter types through their derived decoders, applies the behavior via reflection on
 * the just-generated bytecode ({@link MemoryClassLoader}), and compares the result against the
 * expected arm (a bare type name) or value (a construction/literal). A failing example fails the
 * build, exactly as a false constant invariant does in {@link Compiler#verifyConstConstructions}.
 *
 * <p>Only a behavior with a {@code let} body and no {@code requires} (spec 13.1) can be evaluated;
 * an injected, {@code >->}, or dependency-taking target is refused with a reason ({@code E1902}).
 * Inputs and expected values are fixtures — literals, newtype constructions, and record
 * constructions — not computed expressions.
 */
public final class ExampleVerifier {

    /** Evaluates every example in {@code module}; returns one diagnostic per failing example row
     * (empty when all pass). Does not throw for a failed example — the caller aggregates. */
    public static List<Diagnostic> check(Ast.Module module, Map<String, Ast.Def> symbols,
                                         Map<String, TypeChecker.Sig> sigs, Map<String, byte[]> classes) {
        if (module.examples().isEmpty()) {
            return List.of();
        }
        MemoryClassLoader loader = new MemoryClassLoader(classes, ExampleVerifier.class.getClassLoader());
        ExampleVerifier v = new ExampleVerifier(module, symbols, sigs, loader);
        List<Diagnostic> failures = new ArrayList<>();
        for (Ast.Example ex : module.examples()) {
            try {
                v.checkExample(ex, failures);
            } catch (LinkageError le) {
                // The runtime is not on this host's classpath (it is `provided`, like CTFE), so the
                // generated classes cannot be loaded to evaluate here; the build-time pass, where the
                // runtime is present, still checks this example.
            }
        }
        return failures;
    }

    /** Runs {@link #check} and, if any example failed, fails the build with an aggregated error. */
    public static void verify(Ast.Module module, Map<String, Ast.Def> symbols,
                              Map<String, TypeChecker.Sig> sigs, Map<String, byte[]> classes) {
        List<Diagnostic> failures = check(module, symbols, sigs, classes);
        if (failures.isEmpty()) {
            return;
        }
        // The diagnostic infrastructure carries one diagnostic per exception; report the first and
        // summarize the rest in its hint so a single build surfaces every failing example.
        Diagnostic first = failures.get(0);
        if (failures.size() == 1) {
            throw new CompileException(first, legacyOf(first));
        }
        Diagnostic aggregate = Diagnostic.of(first.code(), "check.example.failed.more")
                .title("check.example.title")
                .at(first.region())
                .args(failures.size())
                .hint("check.example.failed.more.hint", failures.size() - 1)
                .diff(first.diff() == null ? "" : first.diff().actualType(),
                        first.diff() == null ? "" : first.diff().expectedType())
                .build();
        throw new CompileException(aggregate, failures.size() + " examples do not hold; " + legacyOf(first));
    }

    /** A one-line message for a failing example, used where only the legacy string is shown (the LSP
     * surfaces this rather than the rendered catalog message). */
    private static String legacyOf(Diagnostic d) {
        if (d.diff() != null) {
            // JUnit order: the expected value (what the example asserts) first, then what the
            // behavior actually produced.
            return "example does not hold: expected " + d.diff().expectedType()
                    + " but was " + d.diff().actualType();
        }
        return "example failed";
    }

    private final Ast.Module module;
    private final Map<String, Ast.Def> symbols;
    private final Map<String, TypeChecker.Sig> sigs;
    private final MemoryClassLoader loader;

    private ExampleVerifier(Ast.Module module, Map<String, Ast.Def> symbols,
                            Map<String, TypeChecker.Sig> sigs, MemoryClassLoader loader) {
        this.module = module;
        this.symbols = symbols;
        this.sigs = sigs;
        this.loader = loader;
    }

    // --- one example (a target and its rows) --------------------------------------------------

    private void checkExample(Ast.Example ex, List<Diagnostic> out) {
        String target = ex.target();
        Ast.SpecBehavior spec = runnableBehavior(target);
        if (spec == null) {
            out.add(notRunnable(ex));
            return;
        }
        TypeChecker.Sig sig = sigs.get(target);
        Set<String> outCases = outCases(sig.out());
        for (Ast.ExampleRow row : ex.rows()) {
            checkRow(target, spec, sig, outCases, row, out);
        }
    }

    /** The target as a runnable behavior (a {@code let} body, no {@code requires}), or null. */
    private Ast.SpecBehavior runnableBehavior(String name) {
        Set<String> implemented = new java.util.HashSet<>();
        for (Ast.FnDef f : module.fns()) {
            implemented.add(f.name());
        }
        for (Ast.BehaviorDef b : module.behaviors()) {
            if (b instanceof Ast.SpecBehavior spec && spec.name().equals(name)
                    && implemented.contains(name) && spec.requires().isEmpty()) {
                return spec;
            }
        }
        return null;
    }

    /** The diagnostic for a target that cannot be evaluated: unknown (E1901) or present but not a
     * runnable behavior (E1902), with the reason (injected / pipeline / requires). */
    private Diagnostic notRunnable(Ast.Example ex) {
        String name = ex.target();
        boolean known = false;
        String reason = null;
        for (Ast.BehaviorDef b : module.behaviors()) {
            if (!b.name().equals(name)) {
                continue;
            }
            known = true;
            if (b instanceof Ast.PipeBehavior) {
                reason = "it is a `>->` pipeline";
            } else if (b instanceof Ast.SpecBehavior spec) {
                boolean implemented = module.fns().stream().anyMatch(f -> f.name().equals(name));
                if (!implemented) {
                    reason = "it is injected from Java (no `let`)";
                } else if (!spec.requires().isEmpty()) {
                    reason = "it requires injected dependencies (" + String.join(", ", spec.requires()) + ")";
                }
            }
        }
        boolean isHelper = module.fns().stream().anyMatch(f -> f.name().equals(name)
                && module.behaviors().stream().noneMatch(b -> b.name().equals(name)));
        if (isHelper) {
            known = true;
            reason = "a pure helper example is not evaluated yet";
        }
        if (!known) {
            return Diagnostic.of("E1901", "check.example.unknown").title("check.example.title")
                    .at(ex.pos()).args(name).build();
        }
        return Diagnostic.of("E1902", "check.example.notrunnable").title("check.example.title")
                .at(ex.pos()).args(name)
                .hint("check.example.notrunnable.hint", reason == null ? "it is not runnable" : reason)
                .build();
    }

    // --- one row ------------------------------------------------------------------------------

    private void checkRow(String target, Ast.SpecBehavior spec, TypeChecker.Sig sig,
                          Set<String> outCases, Ast.ExampleRow row, List<Diagnostic> out) {
        List<Type> ins = sig.ins();
        if (row.inputs().size() != ins.size()) {
            out.add(Diagnostic.of("E1903", "check.example.arity").title("check.example.title")
                    .at(row.pos()).args(target, ins.size(), row.inputs().size()).build());
            return;
        }
        Object[] args = new Object[ins.size()];
        for (int i = 0; i < ins.size(); i++) {
            try {
                Object raw = raw(row.inputs().get(i));
                args[i] = decode(ins.get(i), raw);
            } catch (FixtureException fe) {
                out.add(Diagnostic.of("E1903", "check.example.input").title("check.example.title")
                        .at(row.pos()).args(target, i + 1, fe.getMessage()).build());
                return;
            }
        }
        // validate the expected arm/value against the output cases before running
        String expectedArm = expectedArm(row.expected());
        if (expectedArm != null && !outCases.isEmpty() && !outCases.contains(expectedArm)) {
            out.add(Diagnostic.of("E1904", "check.example.arm").title("check.example.title")
                    .at(row.pos()).args(expectedArm, target)
                    .hint("check.example.arm.hint", String.join(", ", outCases)).build());
            return;
        }
        Object result;
        try {
            result = invoke(target, args);
        } catch (AbortException ae) {
            out.add(mismatch(row, describeExpected(row.expected()), "aborted: " + ae.getMessage()));
            return;
        }
        if (!matches(row.expected(), result)) {
            out.add(mismatch(row, describeExpected(row.expected()), describeActual(result)));
        }
    }

    private Diagnostic mismatch(Ast.ExampleRow row, String expected, String actual) {
        // Underline the expected result (the part the row asserts), not the whole row, so the marker
        // lands on something meaningful rather than a single column at the row's start.
        SourcePos pos = row.expected() != null ? row.expected().pos() : row.pos();
        int width = Math.max(1, expected.length());
        Diagnostic.Builder b = Diagnostic.of("E1905", "check.example.mismatch")
                .title("check.example.title")
                .at(pos, width)
                .diff(actual, expected);
        if (row.description() != null) {
            b.hint("check.example.mismatch.hint", row.description());
        }
        return b.build();
    }

    // --- comparison ---------------------------------------------------------------------------

    /** Whether {@code result} matches the row's expected: a bare {@link Ast.Var} asserts only the
     * arm (the concrete case class); anything else asserts the whole value by structural equality. */
    private boolean matches(Ast.Expr expected, Object result) {
        if (expected instanceof Ast.Var v) {
            return simpleName(result).equals(v.name());
        }
        Object expectedValue = buildExpected(expected);
        return expectedValue != null && expectedValue.equals(result);
    }

    /** The expected value built the same way as an input, so structural equality compares like with
     * like: a construction/newtype decodes through its type's decoder; a literal is its raw value. */
    private Object buildExpected(Ast.Expr expected) {
        try {
            if (expected instanceof Ast.NewData nd) {
                return decode(Type.ref(nd.typeName()), raw(expected));
            }
            if (expected instanceof Ast.Call c && isNewtype(c.fn())) {
                return decode(Type.ref(c.fn()), raw(expected));
            }
            return raw(expected);   // a literal expected value
        } catch (FixtureException fe) {
            return null;
        }
    }

    /** The arm name an expected asserts: a bare type name, or a construction's/newtype's type name. */
    private String expectedArm(Ast.Expr expected) {
        if (expected instanceof Ast.Var v) {
            return v.name();
        }
        if (expected instanceof Ast.NewData nd) {
            return nd.typeName();
        }
        if (expected instanceof Ast.Call c && isNewtype(c.fn())) {
            return c.fn();
        }
        return null;   // a literal expected (a primitive output)
    }

    private String describeExpected(Ast.Expr expected) {
        String arm = expectedArm(expected);
        return arm != null ? arm : String.valueOf(rawOrNull(expected));
    }

    private String describeActual(Object result) {
        String name = simpleName(result);
        return name.isEmpty() ? String.valueOf(result) : name;
    }

    private Object rawOrNull(Ast.Expr e) {
        try {
            return raw(e);
        } catch (FixtureException fe) {
            return null;
        }
    }

    private static String simpleName(Object o) {
        if (o == null) {
            return "null";
        }
        String n = o.getClass().getName();
        int dot = n.lastIndexOf('.');
        return dot < 0 ? n : n.substring(dot + 1);
    }

    private Set<String> outCases(Type out) {
        if (out instanceof Type.Union u) {
            return u.members();
        }
        if (out instanceof Type.Ref r) {
            return Set.of(r.name());
        }
        return Set.of();
    }

    // --- raw evaluation of a fixture expression -----------------------------------------------

    /** Turns a fixture expression into its neutral (decoder-input) form: a literal to a boxed value,
     * a newtype construction to its inner value, a record construction to a field map. */
    private Object raw(Ast.Expr e) {
        return switch (e) {
            case Ast.IntLit i -> i.value();
            case Ast.DecimalLit d -> d.value();
            case Ast.StringLit s -> s.value();
            case Ast.BoolLit b -> b.value();
            case Ast.Neg n -> negate(raw(n.operand()));
            case Ast.Binary bin -> fold(bin);
            case Ast.Call c -> newtypeInner(c);
            case Ast.NewData nd -> record(nd);
            case Ast.ListLit l -> {
                List<Object> out = new ArrayList<>();
                for (Ast.Expr el : l.elements()) {
                    out.add(raw(el));
                }
                yield out;
            }
            default -> throw new FixtureException("an example fixture must be a literal or a construction");
        };
    }

    private Object newtypeInner(Ast.Call c) {
        if (!isNewtype(c.fn())) {
            throw new FixtureException("`" + c.fn() + "` is not a newtype; a fixture cannot call it");
        }
        if (c.args().size() != 1) {
            throw new FixtureException("`" + c.fn() + "` takes one argument");
        }
        return raw(c.args().get(0));
    }

    private Object record(Ast.NewData nd) {
        if (!nd.spreads().isEmpty()) {
            throw new FixtureException("a `...spread` cannot be used in an example fixture");
        }
        Map<String, Object> map = new LinkedHashMap<>();
        for (Ast.FieldInit fi : nd.inits()) {
            map.put(fi.name(), raw(fi.value()));
        }
        return map;
    }

    private boolean isNewtype(String name) {
        return symbols.get(name) instanceof Ast.Data d && d.newtype();
    }

    private static Object negate(Object v) {
        if (v instanceof Long l) {
            return -l;
        }
        if (v instanceof BigDecimal d) {
            return d.negate();
        }
        throw new FixtureException("only a number can be negated in a fixture");
    }

    private Object fold(Ast.Binary b) {
        Object l = raw(b.left());
        Object r = raw(b.right());
        if (l instanceof Long x && r instanceof Long y) {
            return switch (b.op()) {
                case ADD -> x + y;
                case SUB -> x - y;
                case MUL -> x * y;
                default -> throw new FixtureException("unsupported arithmetic in a fixture");
            };
        }
        if (l instanceof BigDecimal x && r instanceof BigDecimal y) {
            return switch (b.op()) {
                case ADD -> x.add(y);
                case SUB -> x.subtract(y);
                case MUL -> x.multiply(y);
                default -> throw new FixtureException("unsupported arithmetic in a fixture");
            };
        }
        throw new FixtureException("a fixture can only combine numbers of the same kind");
    }

    // --- decode a raw value into the parameter/expected type ----------------------------------

    private Object decode(Type type, Object raw) {
        Decoder<Object, ?> decoder = decoderFor(type);
        Result<?> result = decoder.decode(raw, net.unit8.raoh.Path.ROOT);
        if (result instanceof Ok<?> ok) {
            return ok.value();
        }
        String detail = ((Err<?>) result).issues().asList().stream()
                .map(net.unit8.raoh.Issue::message)
                .collect(java.util.stream.Collectors.joining("; "));
        throw new FixtureException(detail);
    }

    @SuppressWarnings("unchecked")
    private Decoder<Object, ?> decoderFor(Type type) {
        if (type instanceof Type.Prim prim) {
            return switch (prim) {
                case STRING -> ObjectDecoders.string();
                case INT -> ObjectDecoders.long_();
                case BOOL -> ObjectDecoders.bool();
                case DECIMAL -> ObjectDecoders.decimal();
                case DATE -> ObjectDecoders.date();
                case DATETIME -> ObjectDecoders.dateTime();
                case RAW -> throw new FixtureException("the Raw type cannot be an example input");
            };
        }
        if (type instanceof Type.Ref ref) {
            try {
                Class<?> c = loader.loadClass(module.name() + "." + ref.name());
                return (Decoder<Object, ?>) c.getMethod("decoder").invoke(null);
            } catch (ReflectiveOperationException e) {
                throw new FixtureException("no decoder for `" + ref.name() + "`");
            }
        }
        throw new FixtureException("`" + Type.show(type) + "` is not supported as an example value yet");
    }

    // --- invoke the behavior ------------------------------------------------------------------

    private Object invoke(String behavior, Object[] args) {
        String className = module.name() + "." + behaviorClass(behavior);
        try {
            Class<?> c = loader.loadClass(className);
            Object instance = c.getConstructor().newInstance();
            Class<?>[] paramTypes = new Class<?>[args.length];
            java.util.Arrays.fill(paramTypes, Object.class);
            return c.getMethod("apply", paramTypes).invoke(instance, args);
        } catch (java.lang.reflect.InvocationTargetException ite) {
            Throwable cause = ite.getCause();
            throw new AbortException(cause == null ? "aborted" : String.valueOf(cause.getMessage()));
        } catch (ReflectiveOperationException e) {
            throw new AbortException(String.valueOf(e.getMessage()));
        }
    }

    private static String behaviorClass(String name) {
        return Character.toUpperCase(name.charAt(0)) + name.substring(1);
    }

    /** A fixture that cannot be built (an unsupported form, or an invariant a fixture value breaks). */
    private static final class FixtureException extends RuntimeException {
        FixtureException(String message) {
            super(message);
        }
    }

    /** The behavior aborted while evaluating a row (e.g. an invariant violation) — a failed example. */
    private static final class AbortException extends RuntimeException {
        AbortException(String message) {
            super(message);
        }
    }
}
